services:
  wordpress:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
  swag:
    image: linuxserver/letsencrypt
    container_name: swag
    depends_on:
      - wordpress
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=und2telematica.tk
      - SUBDOMAINS=www
      - VALIDATION=http
    volumes:
      - ./config:/config
      - ./default:/config/nginx/site-confs/default
    ports:
      - 443:443
      - 80:80
volumes:
  wordpress:
  db:
